data_path:
  raw: "/content/drive/MyDrive/data/raw/"
  processed: "/content/drive/MyDrive/data/processed/"
preprocessing:
  chunk_size: 1000
  stop_words: ["the", "and", "is", "in", "to", "of"]
logging:
  level: "INFO"
